In [1]:
import pandas as pd

In [2]:
c= pd.read_csv('Downloads/c.csv')
c

,Unnamed: 0,Group,Campus,District,DistName,Region,SAT_Reading,SAT_Math,Total,Above_Crit_Rate,Above_TSI_Both_Rate,English,ACT_Math,Reading,Science,Compos,Latitude,Longitude
0,0,Asian,2901001,2901,Andrews ISD,18,525,516,1041,100.0,100.0,20.8,21.6,23.5,22.7,22.3,32.347703,-102.714199
1,1,Multiracial,13901001,13901,Beeville ISD,2,580,530,1110,33.3,33.3,25.0,21.7,25.7,21.0,23.3,28.417209,-97.655841
2,2,Missing Ethnicity,13901001,13901,Beeville ISD,2,580,530,1110,33.3,33.3,25.0,21.7,25.7,21.0,23.3,28.417209,-97.655841
3,3,Asian,14908001,14908,Salado ISD,12,583,559,1142,100.0,100.0,22.8,25.2,25.7,25.6,25.0,30.941121,-97.591584
4,4,American Indian,15907023,15907,San Antonio ISD,20,588,573,1161,100.0,100.0,24.3,24.1,25.2,23.7,24.3,29.409303,-98.463329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,220,Special Ed,236902008,236902,Huntsville ISD,6,490,475,965,100.0,100.0,21.9,21.1,24.8,23.5,22.9,NaN,NaN
221,221,Migrant,240901002,240901,Laredo ISD,1,555,605,1160,50.0,50.0,18.0,23.0,23.5,21.5,21.5,NaN,NaN
222,222,African American,252901001,252901,Graham ISD,9,535,529,1065,100.0,100.0,20.1,22.3,23.3,23.5,22.4,NaN,NaN
223,223,American Indian,252901001,252901,Graham ISD,9,535,529,1065,100.0,100.0,20.1,22.3,23.3,23.5,22.4,NaN,NaN
224,224,Asian,252901001,252901,Graham ISD,9,535,529,1065,100.0,100.0,20.1,22.3,23.3,23.5,22.4,NaN,NaN

In [3]:
d= pd.read_csv('Downloads/d.csv')
d

,Unnamed: 0,Group,District,DistName,Region,SAT_Reading,SAT_Math,Total,Above_Crit_Rate,Above_TSI_Both_Rate,English,ACT_Math,Reading,Science,Compos,Latitude,Longitude
0,0,Asian,2901,Andrews ISD,18,525,516,1041,100.0,100.0,20.8,21.6,23.5,22.7,22.3,NaN,NaN
1,1,Multiracial,13901,Beeville ISD,2,580,530,1110,33.3,33.3,25.0,21.7,25.7,21.0,23.3,NaN,NaN
2,2,Missing Ethnicity,13901,Beeville ISD,2,580,530,1110,33.3,33.3,25.0,21.7,25.7,21.0,23.3,NaN,NaN
3,3,Asian,14908,Salado ISD,12,583,559,1142,100.0,100.0,22.8,25.2,25.7,25.6,25.0,NaN,NaN
4,4,Multiracial,17901,Borden County ISD,17,626,563,1189,100.0,100.0,22.8,22.4,25.6,23.9,23.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,156,American Indian,227913,Lake Travis ISD,13,520,472,992,100.0,100.0,19.0,19.0,23.7,20.3,20.7,NaN,NaN
157,157,Gifted,229901,Colmesneil ISD,5,590,465,1055,100.0,100.0,19.6,18.9,21.9,20.4,20.3,NaN,NaN
158,158,African American,252901,Graham ISD,9,535,529,1065,100.0,100.0,20.1,22.3,23.3,23.5,22.4,NaN,NaN
159,159,American Indian,252901,Graham ISD,9,535,529,1065,100.0,100.0,20.1,22.3,23.3,23.5,22.4,NaN,NaN
160,160,Asian,252901,Graham ISD,9,535,529,1065,100.0,100.0,20.1,22.3,23.3,23.5,22.4,NaN,NaN

In [4]:
c.shape

(225, 18)

In [5]:
d.shape

(161, 17)

In [6]:
dc= pd.concat([c,d], axis="columns")
dc

,Unnamed: 0,Group,Campus,District,DistName,Region,SAT_Reading,SAT_Math,Total,Above_Crit_Rate,...,Total,Above_Crit_Rate,Above_TSI_Both_Rate,English,ACT_Math,Reading,Science,Compos,Latitude,Longitude
0,0,Asian,2901001,2901,Andrews ISD,18,525,516,1041,100.0,...,1041.0,100.0,100.0,20.8,21.6,23.5,22.7,22.3,NaN,NaN
1,1,Multiracial,13901001,13901,Beeville ISD,2,580,530,1110,33.3,...,1110.0,33.3,33.3,25.0,21.7,25.7,21.0,23.3,NaN,NaN
2,2,Missing Ethnicity,13901001,13901,Beeville ISD,2,580,530,1110,33.3,...,1110.0,33.3,33.3,25.0,21.7,25.7,21.0,23.3,NaN,NaN
3,3,Asian,14908001,14908,Salado ISD,12,583,559,1142,100.0,...,1142.0,100.0,100.0,22.8,25.2,25.7,25.6,25.0,NaN,NaN
4,4,American Indian,15907023,15907,San Antonio ISD,20,588,573,1161,100.0,...,1189.0,100.0,100.0,22.8,22.4,25.6,23.9,23.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,220,Special Ed,236902008,236902,Huntsville ISD,6,490,475,965,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,221,Migrant,240901002,240901,Laredo ISD,1,555,605,1160,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,222,African American,252901001,252901,Graham ISD,9,535,529,1065,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,223,American Indian,252901001,252901,Graham ISD,9,535,529,1065,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,224,Asian,252901001,252901,Graham ISD,9,535,529,1065,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dc.to_csv('dc.csv')

In [10]:
!pip install geopandas

Requirement already satisfied: geopandas in c:\users\sophi\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: shapely>=1.7 in c:\users\sophi\anaconda3\lib\site-packages (from geopandas) (2.0.1)
Requirement already satisfied: packaging in c:\users\sophi\anaconda3\lib\site-packages (from geopandas) (21.3)
Requirement already satisfied: pyproj>=2.6.1.post1 in c:\users\sophi\anaconda3\lib\site-packages (from geopandas) (3.5.0)
Requirement already satisfied: pandas>=1.0.0 in c:\users\sophi\anaconda3\lib\site-packages (from geopandas) (1.4.2)
Requirement already satisfied: fiona>=1.8 in c:\users\sophi\anaconda3\lib\site-packages (from geopandas) (1.9.3)
Requirement already satisfied: click-plugins>=1.0 in c:\users\sophi\anaconda3\lib\site-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: munch>=2.3.2 in c:\users\sophi\anaconda3\lib\site-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: cligj>=0.5 in c:\users\sophi\anaconda3\lib\site-packages (from fiona>=1.8->geopandas) (0.7.2)
Requirement already satisfied: click~=8.0 in c:\users\sophi\anaconda3\lib\site-packages (from fiona>=1.8->geopandas) (8.0.4)
Requirement already satisfied: importlib-metadata in c:\users\sophi\anaconda3\lib\site-packages (from fiona>=1.8->geopandas) (4.11.3)
Requirement already satisfied: attrs>=19.2.0 in c:\users\sophi\anaconda3\lib\site-packages (from fiona>=1.8->geopandas) (21.4.0)
Requirement already satisfied: certifi in c:\users\sophi\anaconda3\lib\site-packages (from fiona>=1.8->geopandas) (2021.10.8)
Requirement already satisfied: colorama in c:\users\sophi\anaconda3\lib\site-packages (from click~=8.0->fiona>=1.8->geopandas) (0.4.4)
Requirement already satisfied: six in c:\users\sophi\anaconda3\lib\site-packages (from munch>=2.3.2->fiona>=1.8->geopandas) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sophi\anaconda3\lib\site-packages (from pandas>=1.0.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sophi\anaconda3\lib\site-packages (from pandas>=1.0.0->geopandas) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in c:\users\sophi\anaconda3\lib\site-packages (from pandas>=1.0.0->geopandas) (1.21.5)
Requirement already satisfied: zipp>=0.5 in c:\users\sophi\anaconda3\lib\site-packages (from importlib-metadata->fiona>=1.8->geopandas) (3.7.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\sophi\anaconda3\lib\site-packages (from packaging->geopandas) (3.0.4)